apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-hybrid
  region: ap-southeast-2
  version: "1.32"

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: ng-dev
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    privateNetworking: false
    volumeSize: 30
    ssh:
      allow: false

iam:
  withOIDC: true
